### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [xdid-net/gtm-xdid#1]
https://github.com/xdid-net/gtm-xdid/blob/b52db1fa68b481da2e4d79af23579a7fd32c3805/template.tpl#L48

When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by xdid-net** [comment]
Fixed in the new version

**Comment by xdid-net** [comment]
Fixed with new version

**Comment by xdid-net** [comment]
Fixed with new version
